-- Seed dummy candidate data for testing
-- Note: Using placeholder URLs for profile pictures and resumes

INSERT INTO candidates (
  user_id,
  email,
  full_name,
  job_title,
  age,
  nationality,
  location,
  phone,
  years_of_experience,
  skills,
  bio,
  resume_url,
  resume_filename,
  profile_picture_url,
  created_at
) VALUES
(
  'sarah.ahmed@test.com',
  'sarah.ahmed@test.com',
  'Sarah Ahmed',
  'Senior Full-Stack Developer',
  28,
  'Emirati',
  'Dubai, UAE',
  '+971 50 123 4567',
  5,
  ARRAY['React', 'Node.js', 'TypeScript', 'AWS', 'MongoDB', 'Docker'],
  'Full-stack developer with 5+ years of experience in React, Node.js, and cloud technologies. Passionate about building scalable web applications and mentoring junior developers.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Sarah_Ahmed_Resume.pdf',
  'https://i.pravatar.cc/300?img=1',
  NOW() - INTERVAL '5 days'
),
(
  'mohammed.ali@test.com',
  'mohammed.ali@test.com',
  'Mohammed Ali',
  'Frontend Developer',
  30,
  'Egyptian',
  'Abu Dhabi, UAE',
  '+971 52 234 5678',
  4,
  ARRAY['Vue.js', 'JavaScript', 'CSS', 'Tailwind', 'Figma', 'UI/UX'],
  'Senior frontend developer specializing in modern web applications and user experiences. Love creating pixel-perfect interfaces that users enjoy.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Mohammed_Ali_Resume.pdf',
  'https://i.pravatar.cc/300?img=12',
  NOW() - INTERVAL '4 days'
),
(
  'lisa.chen@test.com',
  'lisa.chen@test.com',
  'Lisa Chen',
  32,
  'Chinese',
  'Dubai, UAE',
  '+971 55 345 6789',
  6,
  ARRAY['Python', 'TensorFlow', 'SQL', 'R', 'Machine Learning', 'Data Science'],
  'Data scientist with expertise in machine learning and AI-driven solutions. Published researcher with experience in predictive analytics and neural networks.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Lisa_Chen_Resume.pdf',
  'https://i.pravatar.cc/300?img=5',
  NOW() - INTERVAL '3 days'
),
(
  'omar.hassan@test.com',
  'omar.hassan@test.com',
  'Omar Hassan',
  27,
  'Jordanian',
  'Sharjah, UAE',
  '+971 50 456 7890',
  3,
  ARRAY['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Linux', 'Terraform'],
  'DevOps engineer passionate about automation, CI/CD, and cloud infrastructure. Strong believer in infrastructure as code and continuous improvement.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Omar_Hassan_Resume.pdf',
  'https://i.pravatar.cc/300?img=13',
  NOW() - INTERVAL '2 days'
),
(
  'emma.wilson@test.com',
  'emma.wilson@test.com',
  'Emma Wilson',
  29,
  'British',
  'Dubai, UAE',
  '+971 54 567 8901',
  4,
  ARRAY['Figma', 'Adobe XD', 'Sketch', 'Design Systems', 'Prototyping', 'User Research'],
  'UX/UI designer focused on creating intuitive and beautiful digital experiences. Experienced in conducting user research and building design systems.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Emma_Wilson_Resume.pdf',
  'https://i.pravatar.cc/300?img=9',
  NOW() - INTERVAL '1 day'
),
(
  'ahmed.ibrahim@test.com',
  'ahmed.ibrahim@test.com',
  'Ahmed Ibrahim',
  34,
  'Saudi Arabian',
  'Dubai, UAE',
  '+971 50 678 9012',
  7,
  ARRAY['Java', 'Spring Boot', 'Microservices', 'Redis', 'PostgreSQL', 'Kafka'],
  'Backend engineer with strong experience in microservices and distributed systems. Expert in building high-performance, scalable APIs.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Ahmed_Ibrahim_Resume.pdf',
  'https://i.pravatar.cc/300?img=14',
  NOW() - INTERVAL '6 days'
),
(
  'priya.sharma@test.com',
  'priya.sharma@test.com',
  'Priya Sharma',
  26,
  'Indian',
  'Dubai, UAE',
  '+971 55 789 0123',
  3,
  ARRAY['Flutter', 'Dart', 'React Native', 'iOS', 'Android', 'Firebase'],
  'Mobile developer specializing in cross-platform applications. Built and shipped 15+ apps with millions of downloads combined.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Priya_Sharma_Resume.pdf',
  'https://i.pravatar.cc/300?img=10',
  NOW() - INTERVAL '7 days'
),
(
  'carlos.rodriguez@test.com',
  'carlos.rodriguez@test.com',
  'Carlos Rodriguez',
  31,
  'Spanish',
  'Abu Dhabi, UAE',
  '+971 52 890 1234',
  5,
  ARRAY['Cybersecurity', 'Penetration Testing', 'CISSP', 'Network Security', 'Ethical Hacking'],
  'Cybersecurity specialist with CISSP certification. Experience in securing enterprise applications and conducting security audits.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Carlos_Rodriguez_Resume.pdf',
  'https://i.pravatar.cc/300?img=15',
  NOW() - INTERVAL '8 days'
),
(
  'fatima.ali@test.com',
  'fatima.ali@test.com',
  'Fatima Ali',
  25,
  'Lebanese',
  'Dubai, UAE',
  '+971 50 901 2345',
  2,
  ARRAY['Solidity', 'Blockchain', 'Web3', 'Smart Contracts', 'Ethereum'],
  'Blockchain developer passionate about decentralized technologies. Developed multiple DeFi protocols and NFT marketplaces.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Fatima_Ali_Resume.pdf',
  'https://i.pravatar.cc/300?img=20',
  NOW() - INTERVAL '9 days'
),
(
  'james.kim@test.com',
  'james.kim@test.com',
  'James Kim',
  35,
  'Korean',
  'Dubai, UAE',
  '+971 54 012 3456',
  10,
  ARRAY['Project Management', 'Agile', 'Scrum', 'JIRA', 'Leadership', 'Product Strategy'],
  'Technical project manager with 10+ years leading cross-functional teams. PMP certified with track record of delivering complex projects on time.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'James_Kim_Resume.pdf',
  'https://i.pravatar.cc/300?img=17',
  NOW() - INTERVAL '10 days'
),
(
  'layla.hassan@test.com',
  'layla.hassan@test.com',
  'Layla Hassan',
  27,
  'Emirati',
  'Abu Dhabi, UAE',
  '+971 55 123 4567',
  4,
  ARRAY['Content Writing', 'SEO', 'Digital Marketing', 'Social Media', 'Copywriting'],
  'Content strategist and digital marketer with expertise in SEO and social media growth. Helped brands increase organic traffic by 300%+.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'Layla_Hassan_Resume.pdf',
  'https://i.pravatar.cc/300?img=23',
  NOW() - INTERVAL '11 days'
),
(
  'david.chen@test.com',
  'david.chen@test.com',
  'David Chen',
  29,
  'Singaporean',
  'Dubai, UAE',
  '+971 50 234 5678',
  6,
  ARRAY['PHP', 'Laravel', 'MySQL', 'REST API', 'GraphQL', 'Redis'],
  'Senior backend developer with deep expertise in Laravel and API development. Built platforms serving millions of users daily.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'David_Chen_Resume.pdf',
  'https://i.pravatar.cc/300?img=18',
  NOW() - INTERVAL '12 days'
);

-- Success message
SELECT 'Successfully inserted 12 dummy candidates!' as message;
