export const professions = [
  "Software Engineering",
  "Data Science & Analytics",
  "Product Management",
  "Design (UI/UX)",
  "Marketing",
  "Sales",
  "Customer Support",
  "Human Resources",
  "Finance & Accounting",
  "Operations",
  "Business Development",
  "Project Management",
  "Quality Assurance",
  "DevOps & Infrastructure",
  "Cybersecurity",
  "Legal",
  "Consulting",
  "Education & Training",
  "Healthcare",
  "Engineering (Non-Software)",
  "Manufacturing",
  "Hospitality",
  "Retail",
  "Real Estate",
  "Media & Communications",
  "Other",
] as const;

export type Profession = (typeof professions)[number];
